{% set name = "biothings_client" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/biothings_client-{{ version }}.tar.gz
  sha256: c972bf2e02b6f9cc78f7f2fbc5ef02cc56fe4f8a2adcb8801ec902f4ab7011e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.3.0
    - pandas >=0.18.0
    - pyld >=0.7.2
    - requests-cache >=0.4.13

test:
  imports:
    - biothings_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biothings/biothings_client.py
  summary: Python Client for BioThings API services.
  license: BSD-2-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
