{% set name = "biothings_client" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/biothings_client-{{ version }}.tar.gz
  sha256: 0795d4181fa4850ba4688113d28233b37709e560a5b0cfb83a4ff07a715e969c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.3.0
    - pandas >=0.18.0
    - pyld >=0.7.2
    - requests-cache >=0.4.13

test:
  imports:
    - biothings_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biothings/biothings_client.py
  summary: Python Client for BioThings API services.
  license: BSD-2-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
