context:
  name: biothings_client
  version: 0.2.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/biothings_client-${{ version }}.tar.gz
  sha256: 84d9d577b8fb3963a2fa71c5a13b10411566f3bc2e8ba67bb15de9d2ced08c2d

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.3.0
    - pandas >=0.18.0
    - pyld >=0.7.2
    - requests-cache >=0.4.13

tests:
  - python:
      imports:
        - biothings_client
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Python Client for BioThings API services.
  license: BSD-2-Clause
  license_file:
    - LICENSE.txt
  homepage: https://github.com/biothings/biothings_client.py

extra:
  recipe-maintainers:
    - hadim
